name: imas_composer

channels:
  - ga-fdp
  - conda-forge

dependencies:
  # Core runtime deps
  - python >=3.11
  - numpy >=1.24
  - pyyaml *
  - awkward *
  - scipy *

  # Test tools
  - pytest *
  - pytest-benchmark *
  - pytest-xdist *
  - pexpect *
  - tqdm *

  # Default fetching backend
  # fdp requirements (fdp itself is pip-installed from fdp_submodule,
  # not conda, to match the unreleased toksearch above)
  - xrdcl-pelican-fdp
  - fdp-schema >=0.2.1
  - pelicanplatform >=7.24.3,<8 # also required by fdp

   # mdsip-fdp with normal MDSplus
  - mdsplus >=7.157
  - mdsip-fdp

  # For pip install
  - pip *
  - setuptools
  - contourpy
  - pyqtgraph
  - pyodbc
  - pyqt