name: imas_composer

channels:
  - conda-forge

dependencies:
  # Core runtime deps
  - python >=3.11
  - numpy >=1.24
  - pyyaml *
  - awkward *
  - scipy *

  # Test tools
  - pytest *
  - pytest-benchmark *
  - pytest-xdist *
  - pexpect *
  - tqdm *
  - mdsplus =7.157.0

  # For pip install
  - pip *
  - setuptools
  - contourpy
  - pyqtgraph
  - pyodbc
  - pyqt

# # OMAS dependencies- available on conda-forge since 0.95.2
  - boto3
  - botocore
  - cython
  - dnspython
  - matplotlib-base
  - netcdf4
  - pinty
  - pymongo
  - pyro5
  - uncertainties
  - xarray
  - xmltodict