name: imas_composer

channels:
  - conda-forge

dependencies:
  # Core runtime deps
  - python >=3.11
  - numpy >=1.24
  - pyyaml *
  - awkward *
  - scipy *

  # Test tools
  - pip *
  - pytest *
  - pytest-benchmark *
  - pytest-xdist *
  - pexpect *
  - tqdm *
  - mdsplus =7.157.0

  # OMAS - available on conda-forge since 0.95.2
  - omas >=0.95.2
